version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./www:/www
